version: '3.8'
services:
  db:
    env_file: .env
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    container_name: node_app
    build: .
    environment: 
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      DOMAIN: ${DOMAIN}
      PORT: ${PORT}
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["bash", "./wait-for-it.sh", "db:3306", "--", "npm", "run", "dev"]


volumes:
  mysql-data:
